<?php require_once './templates/header.phtml'; ?>

    <div class="about">

    <h2>¡Bienvenido a Nuestra Tienda de Ropa!</h2>

<p>¡Bienvenido a la Tienda de Ropa Diversa, tu destino para encontrar una amplia variedad de prendas de vestir y accesorios
    de moda! Nuestra colección abarca desde ropa casual hasta elegantes trajes y todo lo que puedas imaginar.</p>

<h2>Historia</h2>

<p>Nuestra tienda de ropa tiene una rica historia que se remonta a su fundación en 2001. Desde entonces, hemos estado
    comprometidos en proporcionar a nuestros clientes las últimas tendencias en moda. Inicialmente, comenzamos como una
    modesta tienda en una esquina de la ciudad, pero con el tiempo, hemos crecido y diversificado nuestra colección para
    abarcar todas las necesidades de moda imaginables.</p>

<h2>Misión y Visión</h2>

<p>Nuestra misión es ayudarte a lucir bien y sentirte confiado ofreciendo una amplia variedad de prendas de vestir y
    accesorios a la moda. Buscamos ser tu fuente de inspiración y estilo, apoyando tu expresión personal y tu confianza.</p>

<p>Nuestra visión es ser un referente en la moda y ayudarte a encontrar tu propio estilo único. Nos esforzamos por ser un
    lugar en el que puedas descubrir las últimas tendencias y expresar tu individualidad a través de la moda.</p>

<h2>Valores</h2>

<ul>
    <li><strong>Variedad de Estilos:</strong> Creemos en la importancia de ofrecer una amplia gama de estilos y tendencias
        para satisfacer los gustos de nuestros clientes.</li>

    <li><strong>Accesibilidad:</strong> Nos comprometemos a proporcionar prendas de calidad a precios asequibles para
        todos.</li>

    <li><strong>Servicio al Cliente:</strong> Nuestro equipo está dedicado a brindar un servicio excepcional y asesoramiento
        en moda a nuestros clientes.</li>

    <li><strong>Calidad y Estilo:</strong> Valoramos la calidad de nuestras prendas y la importancia de estar a la moda.</li>

    <li><strong>Comunidad de la Moda:</strong> Fomentamos la creación de una comunidad de amantes de la moda que puedan
        compartir su estilo y conocimientos.</li>
</ul>

<p>Esperamos que esta breve introducción te ofrezca una visión clara de lo que representa la Tienda de Ropa Diversa y cómo
    estamos comprometidos a ayudarte a estar a la moda. Si tienes alguna pregunta o necesitas más información, no dudes en
    ponerte en contacto con nosotros.</p>

<?php require_once './templates/footer.phtml'; ?>