<?php require_once './templates/Header.phtml';?>

<h4>Listado de prendas: </h4>
<table class="table table-striped ">
    <thead>
        <tr>

            <th class="col-sm-4">Marca</th>

            <th class="col-sm-4">Prenda</th>

            <th class="col-sm-4">Talle</th>

            <th class="col-sm-4">Precio</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($ropaData as $ropa) {
            $marca_id = $ropa['marca_id'];
            $prenda = $ropa['prenda'];
            $talle = $ropa['talle'];
            $precio = $ropa['precio'];
        ?>
            <tr>
                <td><?php echo $marca_id ?></td>
                <td><?php echo $prenda ?></td>
                <td><?php echo $talle ?></td>
                <td><?php echo $precio ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
 <!-- problemas a la hora de obtener la informacion -->


<?php require_once './templates/Footer.phtml'; ?>